#!/bin/sh
#
cmd=$(which tmux)      # tmux path

if [ -z $cmd ]; then
    echo "You need to install tmux."
    exit 1
fi

if [ "$1" ]; then
    session=$1
else 
    session=$(date "+%s")
fi

$cmd has -t $session 2> /dev/null

if [ $? != 0 ]; then
    $cmd new -d -s $session 
    $cmd splitw -v -l 7 -t $session
    $cmd splitw -t $session:.0 -h -l 45
    $cmd selectp -t $session:.0
   # $cmd new -d -n vim -s $session "vim"
   # $cmd neww -n irc -t $session "irssi"
   # $cmd neww -n top -t $session "htop"
   # #$cmd splitw -v -p 98 -t $session "zsh"
   # $cmd neww -n zsh -t $session "zsh"
   # $cmd selectw -t $session:5
fi
$cmd ls
$cmd att -t $session

exit 0 

